version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: crud-tecno2-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: sample-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      # En el contenedor "mongo", la base de datos estará disponible con este host
      MONGO_URI: "mongodb://mongo:27017/crud-test"
      PORT: "3000"

volumes:
  mongo-data:
